name: 🚀 Declaration Management Request
description: Add, Update, or Delete entries without using tables or pipes.
title: "Declaration: [Country Code]"
labels: ["migration-request"]
body:
  - type: markdown
    attributes:
      value: |
        ### 📖 Quick Guide
        Fill out only the section relevant to your request. No special formatting is required!
  - type: dropdown
    id: action
    attributes:
      label: "What is the primary action?"
      options:
        - Add New Entries
        - Update Existing Entries
        - Delete Entries
    validations:
      required: true
  - type: input
    id: country_code
    attributes:
      label: "Country Code"
      placeholder: "e.g., ES"
    validations:
      required: true
  - type: textarea
    id: add_section
    attributes:
      label: "🟢 1. ADD: New Entry Details"
      description: "List the new entries. One per line."
      placeholder: "MessageType: CC415A, Name: Standard declaration, Group: Standard"
  - type: textarea
    id: update_section
    attributes:
      label: "🟡 2. UPDATE: Existing Entries"
      description: "Specify which MessageType to change and what the new values should be."
      placeholder: |
        FIND MessageType: CC415A
        CHANGE Name TO: Revised Standard Declaration
        CHANGE Group TO: Simplified
  - type: textarea
    id: delete_section
    attributes:
      label: "🔴 3. DELETE: Remove Entries"
      description: "List the MessageTypes that should be removed."
      placeholder: "Delete MessageType: CC999B"
  - type: textarea
    id: justification
    attributes:
      label: "Business Justification"
      placeholder: "Why are these changes needed? (e.g., Faster country onboarding)"
