name: 🚀 Declaration Management Request
description: The easiest way to Add, Update, or Delete keys without using tables or pipes.
title: "Declaration: [Country Name]"
labels: ["migration-request"]
body:
  - type: markdown
    attributes:
      value: |
        ### 📖 Quick Guide
        Fill out the fields below. No special formatting or "pipes" (|) are required!

  - type: dropdown
    id: action
    attributes:
      label: "What is the primary action?"
      options:
        - Add New Entries
        - Update Existing Entries
        - Delete Entries
    validations:
      required: true

  - type: input
    id: country_code
    attributes:
      label: "Country Code"
      placeholder: "e.g., ES"
    validations:
      required: true

  - type: textarea
    id: entry_list
    attributes:
      label: "Entry Details"
      description: "List the MessageType and MessageName here. If adding multiple, put each on a new line."
      placeholder: |
        MessageType: CC415A, Name: Standard declaration
        MessageType: CC415B, Name: Simplified declaration
    validations:
      required: true

  - type: textarea
    id: additional_metadata
    attributes:
      label: "Additional Details (Optional)"
      description: "Any extra info like ProcedureGroup or ValidFrom dates."
      placeholder: "ProcedureGroup: Standard, ValidFrom: 0001-01-01"

  - type: textarea
    id: justification
    attributes:
      label: "Business Justification"
      placeholder: "Why are these changes needed? (e.g., New country onboarding)"
