name: 游 Declaration Management Request
description: Use specific lookup fields to Add, Update, or Delete keys.
title: "Declaration: [Country Name]"
labels: ["migration-request"]
body:
  - type: markdown
    attributes:
      value: |
        ### 游닀 BA Instructions
        Check the box for the action you want to perform, then fill in the corresponding table below.

  - type: checkboxes
    id: actions_to_perform
    attributes:
      label: "Select Operations"
      description: "Select which actions are included in this request."
      options:
        - label: "游릭 I am ADDING new entries"
        - label: "游리 I am UPDATING existing entries"
        - label: "游댮 I am DELETING entries"

  - type: textarea
    id: add_table
    attributes:
      label: "游릭 ADD: New Entries"
      description: "Fill this if the 'Add' checkbox is selected."
      value: |
        | Country | Procedure | MessageType | MessageTypeCategory | MessageName | ProcedureGroup | ValidFrom |
        | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
        | | | | | | | |

  - type: markdown
    attributes:
      value: "### 游리 UPDATE: Existing Entries"

  - type: textarea
    id: update_find_table
    attributes:
      label: "1. Find Record (Existing Values)"
      description: "Enter the current values to identify the record."
      value: |
        | [FIND] Country | [FIND] Procedure | [FIND] MessageName | [FIND] MessageTypeCategory |
        | :--- | :--- | :--- | :--- |
        | | | | |

  - type: textarea
    id: update_new_table
    attributes:
      label: "2. Change To (New Values)"
      description: "Enter the new values for the record found above."
      value: |
        | [NEW] MessageType | [NEW] MessageTypeCategory | [NEW] MessageName | [NEW] ProcedureGroup |
        | :--- | :--- | :--- | :--- |
        | | | | |

  - type: textarea
    id: delete_table
    attributes:
      label: "游댮 DELETE: Remove Entries"
      description: "Provide identifiers to remove a record."
      value: |
        | Country | Procedure | MessageName | MessageTypeCategory |
        | :--- | :--- | :--- | :--- |
        | | | | |

  - type: textarea
    id: justification
    attributes:
      label: "Business Justification"
      placeholder: "e.g., Updating Spanish import procedures for 2026."
