name: 🚀 Declaration Management Request
description: Add, Update, or Delete entries in the Declaration Table.
title: "Declaration: [Country Name]"
labels: ["migration-request"]
body:
  - type: dropdown
    id: action
    attributes:
      label: What action do you want to take?
      options:
        - Add New Key
        - Update Existing Key
        - Delete Key
    validations:
      required: true

  - type: textarea
    id: add_table
    attributes:
      label: 🟢 Data for NEW Entries
      description: If you selected "Add New Key", fill out this table. (Do not delete the pipes!)
      value: |
        | Country | Procedure | MessageType | MessageName | ProcedureGroup | ValidFrom |
        | :--- | :--- | :--- | :--- | :--- | :--- |
        | | | | | | |
    validations:
      required: false

  - type: textarea
    id: update_delete
    attributes:
      label: 🟡 Details for Update or Delete
      description: Provide identifiers (Country, MessageType) or specific changes needed.
      placeholder: "e.g. For CC415A, change MessageName to 'Simplified'"
