name: 🚀 Declaration Management Request
description: Use specific lookup fields to Add, Update, or Delete keys.
title: "Declaration: [Country Name]"
labels: ["migration-request"]
body:
  - type: markdown
    attributes:
      value: |
        ### 📖 BA Instructions
        Follow the schema below to manage declaration keys. 
        - **To Update**: Fill in the **FIND** section to locate the record and the **NEW** section for changes.
        - **To Add/Delete**: Use the dedicated tables below.

  - type: textarea
    id: add_table
    attributes:
      label: "🟢 ADD: New Entries"
      value: |
        | Country | Procedure | MessageType | MessageTypeCategory | MessageName | ProcedureGroup | ValidFrom |
        | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
        | | | | | | | |

  - type: textarea
    id: update_table
    attributes:
      label: "🟡 UPDATE: Existing Entries"
      description: "Use the first 4 columns to FIND the record, then specify the changes."
      value: |
        | [FIND] Country | [FIND] Procedure | [FIND] MessageName | [FIND] Category | [NEW] MessageType | [NEW] Group | [NEW] ValidUntil |
        | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
        | | | | | | | |

  - type: textarea
    id: delete_table
    attributes:
      label: "🔴 DELETE: Remove Entries"
      description: "Provide identifiers to remove a record."
      value: |
        | [FIND] Country | [FIND] Procedure | [FIND] MessageName | [FIND] Category |
        | :--- | :--- | :--- | :--- |
        | | | | |

  - type: textarea
    id: justification
    attributes:
      label: "Business Justification"
      placeholder: "e.g., Updating Spanish import procedures for 2026."
