<!DOCTYPE html>
<html>
<head>
    <title>Config Documentation</title>
</head>
<body>

    <h2>Configuration Entry Table</h2>
    <p>Fill in the details for your DbContext settings below:</p>

    <table border="1" id="docTable" style="width:100%; border-collapse: collapse;">
        <thead>
            <tr>
                <th>Setting Name</th>
                <th>Key/Path</th>
                <th>Value (Connection String)</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><input type="text" style="width:95%"></td>
                <td><input type="text" style="width:95%"></td>
                <td><input type="text" style="width:95%"></td>
                <td><button onclick="deleteRow(this)">Remove</button></td>
            </tr>
        </tbody>
    </table>

    <br>
    <button onclick="addRow()">+ Add New Row</button>

    <script>
        function addRow() {
            var table = document.getElementById("docTable").getElementsByTagName('tbody')[0];
            var row = table.insertRow(-1);
            
            // Create 3 input cells
            for (var i = 0; i < 3; i++) {
                var cell = row.insertCell(i);
                var input = document.createElement("input");
                input.type = "text";
                input.style.width = "95%";
                cell.appendChild(input);
            }
            
            // Add the delete button cell
            var actionCell = row.insertCell(3);
            actionCell.innerHTML = '<button onclick="deleteRow(this)">Remove</button>';
        }

        function deleteRow(btn) {
            var row = btn.parentNode.parentNode;
            row.parentNode.removeChild(row);
        }
    </script>

</body>
</html>
