name: 🚀 Declaration Management Request
description: Add, Update, or Delete entries by simply filling in the rows.
title: "Declaration: [Country Name]"
labels: ["migration-request"]
body:
  - type: markdown
    attributes:
      value: |
        ### 💡 Instructions
        Fill in the rows below. If you need more rows, just copy and paste an existing line.
  
  - type: textarea
    id: migration_table
    attributes:
      label: "Migration Data Table"
      description: "Just add your data between the pipes (|)."
      value: |
        | Action (Add/Update/Delete) | Country | Procedure | MessageType | MessageName | ProcedureGroup |
        | :--- | :--- | :--- | :--- | :--- | :--- |
        | Add | | | | | |
        | Update | | | | | |
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional Notes"
      placeholder: "e.g. This is for the new 2026 Spain onboarding."
